### ISSUE TITLE
Problems loading the latest release of the rooms

### ISSUE THREAD

**Issue by AndriuxDev** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#31]
For some god-forsaken reason, I cannot load the rooms as intended. It tells me that some code in the rooms is erroneous. Can you fix that? This applies to:

- [ ] All rooms, regardless of which one is it.

I eagerly await your response.
_-AndriuxDev_

**Comment by Cdino11** [comment]
It means you have duplicate files if I'm not it means the files are somewhere out of their intended folder and location or you renamed the folder. When you updated it caused there to be extra files.

**Comment by Cdino11** [comment]
Please leave the full error trace back here so we can further help you

**Comment by multimokia** [comment]
[Closing as inactive]
