### ISSUE TITLE
Updating the garden view is not working

### ISSUE THREAD

**Issue by PlutoMarionette** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#32]
When I attempt to update garden view, it displays the message "check submod_log.txt" I've added both my .log and .txt files below
[submod_log.log](https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/7617407/submod_log.log)
[submod_log.txt](https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/7617411/submod_log.txt)

**Comment by Cdino11** [comment]
it looks like a onedrive problem from what i can tell. are you able to disable it for MAS

**Comment by PlutoMarionette** [comment]
Sorry that I haven’t been back in a while, but I’m afraid I can’t disable the OneDrive as I use it for schoolwork and the like
