### ISSUE TITLE
I can't launch the game after downloading the mod

### ISSUE THREAD

**Issue by frogkid328** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#38]
<img width="905" alt="Screen Shot 2022-05-12 at 5 49 23 pm" src="https://user-images.githubusercontent.com/105417681/168019447-4246714b-70ed-4b07-ac38-7a254668b0eb.png">
It says this whenever I try launching the game. What's wrong?

**Comment by multimokia** [comment]
It'sl ikely you installed MAS incorrectly. Please validate MAS is installed correctly and no files have been replaced (i.e. the MAS scripts) as Mac does a poor job of file management and tends to _replace_ folders instead of merging them.
