### ISSUE TITLE
keep having errors in the location 

### ISSUE THREAD

**Issue by nguyenkhanhduc** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#40]
so how do i fix this?
![monika bug](https://user-images.githubusercontent.com/71209660/174505357-a8542318-eca5-42c0-aae3-a8df07c2b1ec.PNG)
i have reinstall everything of the mod and still nothing . please help

**Comment by nguyenkhanhduc** [comment]
I have removed all the room bc all of it was a bug in the init -1 python LIKE ALL Of it but still hoping that I can get help  
thank you

**Comment by multimokia** [comment]
Seems like you just had the submod installed twice.  Since you've uninstalled, attempt to reinstall and it should work fine.
