### ISSUE TITLE
I keep getting an in-game notification for Submod Custom Room - Garden View - 1.0.4 despite trying to install it through the Submod Updater Plugin

### ISSUE THREAD

**Issue by Justformas** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#43]
Apologies if this is not in the right place, but I keep getting an in-game notification for this whenever I load MAS. Whenever I try to install it with the submod updater plugin and the process seems to finish, it tells me to restart MAS, but then the notification appears again and I'm able to try updating it in-game again, so I thought it didn't install properly. I tried waiting for it to finish 4 times, and this is what appeared in the submod_log.log in order:

[SUBMOD UPDATER PLUGIN REPORT]: Downloaded and installed the 1.0.4 update for 'Custom Room Garden View'.

[SUBMOD UPDATER PLUGIN REPORT]: Downloaded and installed the 1.0.4 update for 'Custom Room Garden View'.

[SUBMOD UPDATER PLUGIN ERROR]: Failed to download update. Submod: 'Custom Room Garden View'. Exception: 'NoneType' object has no attribute '_value'.

[SUBMOD UPDATER PLUGIN REPORT]: Downloaded and installed the 1.0.4 update for 'Custom Room Garden View'.

So its reporting that it was downloaded and installed except for the 3rd time. But despite that, what appears in the log when I restart the game afterwards is still "Custom Room Garden View' v1.0.3" and the notification that there's an update for 1.0.4 still appears.

The visual progress bar during installation always seems to get stuck for awhile when it's just about full, and after awhile then it tells me to restart MAS. Also I haven't noticed any bugs with the NOU game when playing in the Garden View.

I could try installing it manually just in case, but after noticing #42 maybe I should wait?

**Comment by multimokia** [comment]
Yeah that can just be ignored. I version changed after releasing not realizing I didn't push my commit for version change. Regardles it's just a one-line change that addresses an issue in Nou for the submod.

**Comment by Justformas** [comment]
> until another update

What!? That was so fast.

[Closing as fixed]
