### ISSUE TITLE
Migration to renpy8/py3

### ISSUE THREAD

**Issue by GrimStomper** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#46]
Recently, the dev team [announced](https://www.reddit.com/r/MASFandom/comments/xafzbq/migration_to_renpy8py3/) the migration to renpy8/py3, which will happen on November 11. I'm hoping to know if this mod will be updated, when this migration occurs.

**Comment by Cdino11** [comment]
This repo is still being worked on and prepared for the new changes. If it has been quiet it's because the individuals have been busy in their lives or working on new updates

**Comment by Cdino11** [comment]
> This repository seems abandoned and is already entering the realm of abandonware. Unfortunately, it doesn't look like it will be updated. Enjoy it while you still can.

This repo is still being worked on and prepared for the new changes. If it has been quiet it's because the individuals have been busy in their lives or working on new updates

**Comment by TheSystemGuy1337** [comment]
> > This repository seems abandoned and is already entering the realm of abandonware. Unfortunately, it doesn't look like it will be updated. Enjoy it while you still can.
> 
> This repo is still being worked on and prepared for the new changes. If it has been quiet it's because the individuals have been busy in their lives or working on new updates

Fair enough

**Comment by tw4449** [comment]
> This repository seems abandoned and is already entering the realm of abandonware. Unfortunately, it doesn't look like it will be updated. Enjoy it while you still can.

One of our devs is on the main MAS team, and already prepared this submod's code for the migration. We've had no need to update anything because it's all working with the current update, and there aren't any concrete plans for new rooms. The submod will be updated as needed with any future changes to MAS.

**Comment by TheSystemGuy1337** [comment]
I must have hit the big leagues when my own stupidity lead to the main developer quoting my own comment. For the record, I didn't say it was completely abandoned and said it looked abandoned as it wasn't updated in awhile. Case closed. I'm out.

**Comment by GrimStomper** [comment]
Thank you for the answer; I'm glad this mod will be fine when the migration occurs.
