### ISSUE TITLE
Garden View Update Breaking Game

### ISSUE THREAD

**Issue by ashyashton** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#48]
I've seen others have similar issues, but not the one I seem to be getting. I tried to bulk update to see if the Garden Room had been fixed, since another submod had also updated, but nope, it's even worse now!

The first one seems to have installed fine. But now it's on the Garden View submod, and it's stuck on "Progress: 1/2; Updating the submod..."

The second bar is full, but it will not go away. I can't close the game because I can't tell Monika goodbye. Not only that, but because it's trying to use the internet, it is now making my internet run at a snail's pace in other applications. This is incredibly frustrating lol, so if anyone could help me figure out how to fix it, please tell me. Otherwise I'll assume the room is a broken submod and delete it.

**Comment by Cdino11** [comment]
It's an issue with the submod updater not the the rooms as they are 2 separate mods. You can simply download the rooms manually here and get the update if it's broken on the updater's end. Just make sure you follow the instructions thoroughly when installing the rooms. I also suggest you leave an issue at the repo for the submod updater

**Comment by Cdino11** [comment]
https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin

This the the link to the submod updater
