### ISSUE TITLE
RPY Error while changing to Spaceroom V1 & V3

### ISSUE THREAD

**Issue by Ggmdark** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#50]
There is some problems with the mod at some locations. Had to manually open the file to fix the error in both Spaceroom V1 and V3 RPY

Adding the **/location/** fixed the issue at least for me. The other locations are working as intended

image V3mas_d25_lights = ConditionSwitch(
    "mas_isNightNow()", ConditionSwitch(
        "persistent._mas_disable_animations", "mod_assets/location/Spaceroom V3.1/deco/d25/V3lights_on_1.png",
        "not persistent._mas_disable_animations", "V3mas_d25_night_lights_atl"
    ),
    "True", MASFilterSwitch("mod_assets/location/Spaceroom V3.1/deco/d25/V3lights_off.png")
)

**Comment by Cdino11** [comment]
ah thank you for noticing

**Comment by Cdino11** [comment]
i'll update soon
