### ISSUE TITLE
FATAL - Adding more than two rooms bricks the game

### ISSUE THREAD

**Issue by TheSystemGuy1337** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#52]
This is a fatal bug. Every time you add two rooms. they will conflict with each over and **BRICK YOUR GAME**

This is completely unacceptable for something like this, especially if your submod has strict quality control. FIX IT.

The label return_switch_dlg is defined twice, at
  File "game/Submods/location_selector/Locatons/Den.rpy", line 274 and
  File "game/Submods/location_selector/Locatons/Furnished_spaceroom3.rpy", line 199.

The label bg_room_installed_low_affection is defined twice, at
  File "game/Submods/location_selector/Locatons/Den.rpy", line 297 and
  File "game/Submods/location_selector/Locatons/Furnished_spaceroom3.rpy", line 222.

The label bg_room_installed is defined twice, at
  File "game/Submods/location_selector/Locatons/Den.rpy", line 339 and
  File "game/Submods/location_selector/Locatons/Furnished_spaceroom3.rpy", line 264.

The label monika_players_control_override is defined twice, at
  File "game/Submods/location_selector/Locatons/Den.rpy", line 383 and
  File "game/Submods/location_selector/Locatons/Furnished_spaceroom3.rpy", line 308.

The label monika_gotomonika_override is defined twice, at
  File "game/Submods/location_selector/Locatons/Den.rpy", line 426 and
  File "game/Submods/location_selector/Locatons/Furnished_spaceroom3.rpy", line 351.

Ren'Py Version: Ren'Py 6.99.12.4.2187

**Comment by TheSystemGuy1337** [comment]
UPDATE: This is practically a clone of https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/issues/47 as this is the same issue, however I closed it as I was asked questions, got irritated and shut it down. Here's some details. I'm running the standard stable MAS

**Comment by Cdino11** [comment]
We apologize for the inconvenience you are experiencing. Thank you for bring this back to our attention so we can address this issue. I will need time to accurately look into your issue. Upon first glance it would seem its is not an issue with our mod directly; rather the build of Monika After Story you are running, as this has rarely been an issue other wise. Older issues resulting in this and similar symptoms were from running the game from a zipped folder, one drive, or a doubled folder. I myself have only ever encountered this exact error when running a dev build version of this game, and have thus far only been able to recreate this error in a dev build. At the current moment I suggest you check to make sure the paths for the game dont double up or repeat, and if that wasn't your issue  then I would further suggest you re-download the game from these links

DDLC: https://teamsalvato.itch.io/ddlc/download/eyJpZCI6MTA2NTk5LCJleHBpcmVzIjoxNjc0MTAyMzk4fQ%3d%3d.TThpWuNBomLwpZfYhHFUMM8gd1E%3d

Monika After Story: https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.12.13

And I urge you to save your:  "mod_assets" folder if you wish to keep your accessories!

Again thank for your notice of this issue! And please remember to give us time to assess this unique error if the aforementioned fixes dont work.

Please keep us updated.

**Comment by TheSystemGuy1337** [comment]
And since you’re going to shoot me for being rude, here’s the problem I found, and it’s a big fat error. You literally duplicated variable names, so if you add them, they will conflict with each over. The fix? Add a number to the variable

**Comment by TheSystemGuy1337** [comment]
Please quit asking questions that you’ve already asked or basically know. This is why I closed the last thread. Asking too many questions irritates me. I’ll say it again since you didn’t see it. I’m running MAS stable 0.12.13, it is not being ran from OneDrive, not being ran from a ZIP file, not in a double folder, not being ran from Steam and I haven’t reinstalled yet since I’ve already found a solution. I’ll say it again: You literally duplicated variable names, so if you add the rooms to the game, the rooms will conflict with each over and grant you the GSOD. The fix? Add a number to the variable so they are all distinct and so they won’t collide with each other.

**Comment by TheSystemGuy1337** [comment]
And to address the repeated dialogue problem, tie the rooms to a watchdog/master control submod, or use internal flags

**Comment by TheSystemGuy1337** [comment]
This issue bit the dust and nobody is here to help (because I was rude about it obviously)
Since nobody gives two damns anymore, this issue is going to suffer the same fate as the last one I made. Thanks for nothing. I’m shutting it down

**Comment by TheSystemGuy1337** [comment]
And due to your ignorance, I’m steering people away from this.

**Comment by TheSystemGuy1337** [comment]
Most of the programming languages I’ve seen go mental on repeated variable names, especially C++
And since you hate me, I might as well suck it up and live with the one room limitation as I will not be reinstalling as I consider it a nuclear solution to an issue so small most people can live with it. Your opinions be solutions are valid
